- name: Installing apache2 in client node
  yum: pkg=httpd state=latest
  notify: 
  - Restart_httpd
#   pkg: httpd
#   state: latest
#  notify: Restart HTTPD
- name: Printing value from vars
  shell: echo "{{copyright}}"
